### ISSUE TITLE
function definition is void: regex-match

### ISSUE THREAD

**Issue by JosephBoyd** [SerialDev/inim-mode#1]
I'm getting the following when trying to eval.

inim-match-indentation: Symbol’s function definition is void: regex-match

nim - 0.19.4
inim - 0.4.1
gnu emacs - 26.2

**Comment by SerialDev** [comment]
Apologies for that one, Resolved with https://github.com/SerialDev/inim-mode/commit/b06eb56325f9e2fda0c84060e9dfbb3d7f68aee9
