### ISSUE TITLE
Inim not starting

### ISSUE THREAD

**Issue by super-tomcat** [SerialDev/inim-mode#2]
Starting Inim with C-p i get this in Messages and nothing in the Inim window...

font-lock-eval-keywords: Symbol’s value as variable is void: nim-mode-font-lock-keywords

**Comment by SerialDev** [comment]
it looks like nim-mode does not expose that functionality now. 
resolved in: https://github.com/SerialDev/inim-mode/commit/feba1d9c55ca43456824faf0faa05e53ebb9f63a
It should work now

**Comment by super-tomcat** [comment]
Inim window opens, but now i get 'current buffer has no process' and you can see that the modeline also says 'no process'...

![inim](https://user-images.githubusercontent.com/30247008/128372069-ac74c392-e516-4d13-86b9-0159d2391a0b.JPG)

Emacs 27.1
Windows 10
